# Generated by Django 2.0.6 on 2018-08-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('html', models.CharField(max_length=400000)),
                ('status_code', models.IntegerField()),
                ('time_elapsed', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('date_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='site_foreign_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dive.Site'),
        ),
    ]
