# Generated by Django 2.0.6 on 2018-08-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='address',
            new_name='site_name',
        ),
    ]
