# Generated by Django 2.0.6 on 2018-08-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dive', '0002_auto_20180830_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site_name',
            new_name='address',
        ),
    ]
